@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()
skinparam backgroundcolor transparent
skinparam ArrowFontColor lightGray
skinparam ArrowColor lightGray
skinparam BoundaryBorderColor red
skinparam DefaultFontColor white

!$COLOR_A_5 = "#7f3b08"
!$COLOR_A_4 = "#b35806"
!$COLOR_A_3 = "#e08214"
!$COLOR_A_2 = "#fdb863"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
!$COLOR_B_1 = "#d8daeb"
!$COLOR_B_2 = "#b2abd2"
!$COLOR_B_3 = "#8073ac"
!$COLOR_B_4 = "#542788"
!$COLOR_B_5 = "#2d004b"
!$COLOR_REL_LINE = "#8073ac"
!$COLOR_REL_TEXT = "#8073ac"

' UpdateElementStyle("person", $bgColor=$COLOR_A_5, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_1, $shadowing="true")

Person(upeStudent, "UPE Student", "A student of UPE, with Unical account" )
System_Ext(gAuth, "Google Authentication API", "API to authenticate user login and/or subscription")
System_Boundary(unical, "Unical UPE System"){
  Container(mobileApp, "Mobile App", "React Native", "Provides full set of Unicall functionalities to users via their mobile device")
  Container(api, "API", "Java(SpringBoot)", "Provides The Events functionality via JSON/HTTPS")
  ContainerDb(db, "Database", "postgresql", "Stores events data and user authentication info")
  
  Rel(mobileApp, api, "Uses", "JSON/HTTPS")
  Rel(api, db, "Reads & writes to", "JDBC")
}

Rel(upeStudent, unical,"Uses", "HTTP")
Rel(mobileApp, gAuth, "Authenticate user", "HTTP")
@enduml