@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(upeStudent, "UPE Student", "A student of UPE, with Unical account" )
System_Ext(gAuth, "Google Authentication API", "API to authenticate user login and/or subscription")
System_Boundary(unical, "Unical UPE System"){
  Container(mobileApp, "Mobile App", "React Native", "Provides full set of Unicall functionalities to users via their mobile device")
  Container(api, "API", "Java(SpringBoot)", "Provides The Events functionality via JSON/HTTPS")
  ContainerDb(db, "Database", "postgresql", "Stores events data and user authentication info")
  
  Rel(mobileApp, api, "Uses", "JSON/HTTPS")
  Rel(api, db, "Reads & writes to", "JDBC")
}

Rel(upeStudent, unical,"Uses", "HTTP")
Rel(unical, gAuth, "Authenticate user", "HTTP")
@enduml