@startuml CONTEXT
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
' LAYOUT_LEFT_RIGHT()
skinparam backgroundcolor transparent
skinparam ArrowFontColor lightGray
skinparam ArrowColor lightGray




Person(upeStudent, "Estudante da UPE", "Um estudante da UPE que possua uma conta no UnicalUPE")
Person(upeProfessor, "Professor da UPE", "Um professor da UPE que possua uma conta no UnicalUPE")
System(unical, "Sistema Unical UPE", "Permite que os usuários visualizem, gerenciem e compartilhem informações sobre eventos universitários")
System_Ext(gAuth, "Google Authentication API", "API para autenticação, login e cadastro")
System_Ext(Expo, "Expo", "Ferramenta utilizada no desenvolvimento mobile que permite acesso as diversas APIs desenvolvidas pelo expo.com")
System_Ext(Heroku, "Heroku", "Heroku é uma plataforma de nuvem como serviço onde é possivel hospedar projetos")


Rel(upeStudent, unical,"Usa")
Rel(upeProfessor, unical,"Usa")
Rel(unical, gAuth, "Atenticação", "HTTP")
Rel(unical, Expo, "Usa")
Rel(unical, Heroku, "Hospedado por")
@enduml
